---

plugins:
  - jest

env:
  node: true
  jest: true

parser: babel-eslint

globals:
  document: true
  DOMParser: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
